# Generated by Django 4.1.8 on 2024-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0004_collection_processing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="api_key",
        ),
        migrations.AddField(
            model_name="collection",
            name="db_storage",
            field=models.CharField(default="chromadb", max_length=255),
            preserve_default=False,
        ),
    ]
