# Generated by Django 4.1.8 on 2024-04-01 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0004_collection_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="db_storage",
            field=models.CharField(default="chromadb", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
