# Generated by Django 4.1.8 on 2024-04-11 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0005_remove_collection_api_key_collection_db_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
