# Generated by Django 4.1.8 on 2024-04-01 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0005_remove_collection_api_key_collection_db_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="id",
        ),
        migrations.AlterField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
