# Generated by Django 4.1.8 on 2024-04-01 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0005_collection_db_storage_alter_collection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
