# Generated by Django 4.1.8 on 2024-04-01 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0006_remove_collection_id_alter_collection_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="uuid",
            new_name="id",
        ),
    ]
