# Generated by Django 4.1.8 on 2024-04-01 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0006_collection_uuid_alter_collection_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="api_key",
        ),
    ]
