# Generated by Django 4.1.8 on 2024-04-01 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0009_rename_uuid_collection_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="id",
            new_name="uuid",
        ),
    ]
