# Generated by Django 4.1.8 on 2024-04-01 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0010_rename_id_collection_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="id",
            field=models.BigAutoField(
                default=1, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
