# Generated by Django 4.1.8 on 2024-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0012_alter_collection_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
