# Generated by Django 4.1.8 on 2024-04-01 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0013_alter_collection_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="uuid",
        ),
    ]
