# Generated by Django 4.1.8 on 2024-04-01 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0014_remove_collection_uuid"),
    ]

    operations = []
