# Generated by Django 4.1.8 on 2024-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0015_auto_20240401_1158"),
    ]

    operations = []
