# Generated by Django 4.1.8 on 2024-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indexes", "0016_auto_20240401_1159"),
    ]

    operations = []
